import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { PDFDocument, rgb } from 'pdf-lib';
import fs from 'fs';
import path from 'path';
import { terbilangRupiah } from '@/lib/terbilang';

// Konversi bulan angka ke Romawi
const getRomawiBulan = (month: number) => {
  const romawi = ["", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII"];
  return romawi[month] || "";
};

export async function POST(request: Request) {
  try {
    const { transactionId } = await request.json();

    if (!transactionId) {
      return NextResponse.json({ error: 'Transaction ID is required' }, { status: 400 });
    }

    const setoran = await prisma.riwayatSetoran.findUnique({
      where: { id: transactionId },
      include: {
        rencana_tabungan: {
          include: {
            jamaah: true,
            paket: true
          }
        }
      }
    });

    if (!setoran) {
      return NextResponse.json({ error: 'Transaction not found' }, { status: 404 });
    }

    const dateObj = new Date(setoran.tanggal_setor);
    const day = String(dateObj.getDate()).padStart(2, '0');
    const month = String(dateObj.getMonth() + 1).padStart(2, '0');
    const year = dateObj.getFullYear();
    const formattedDateStr = `${day}-${month}-${year}`;

    const namaJamaah = setoran.rencana_tabungan.jamaah.nama;
    const nominalAngka = Number(setoran.nominal);
    const terbilangText = terbilangRupiah(nominalAngka);
    const namaPaket = setoran.rencana_tabungan.paket_snapshot_nama || setoran.rencana_tabungan.paket?.nama_paket || "Paket Dihapus";
    const untukTeks = `Pembayaran Paket ${namaPaket}`;

    // 1. Sync with Google Sheets to get the receipt number
    const appScriptUrl = "https://script.google.com/macros/s/AKfycbyJ42CRNj6_zlDVgQRWXCiAkJatvbfyYkAqN9_SwisfIYE8EElT0vsgI3cRyPRf5OtelA/exec";
    
    // We send empty nomor_surat for now, the App Script (if updated) will handle it.
    // We will instruct the user to update the App Script to construct it, OR we can construct it after getting the number.
    // Wait, the currently deployed App Script returns `nextNo`.
    // Let's fetch it first by sending a POST.
    
    const sheetData = {
      tanggal_surat: formattedDateStr,
      nomor_surat: "[Menunggu Nomor]", // Will be generated by Apps Script if updated
      tujuan_surat: namaJamaah,
      perihal: "Kuitansi",
      tanda_tangan: "Direktur Madinah Salam Wisata"
    };

    let nextNo = "000";
    try {
      const response = await fetch(appScriptUrl, {
        method: "POST",
        body: JSON.stringify(sheetData),
        headers: { "Content-Type": "application/json" }
      });
      const resData = await response.json();
      if (resData.status === "success" && resData.nextNo) {
        nextNo = resData.nextNo;
      }
    } catch (err) {
      console.error("Failed to sync with Google Sheets:", err);
      // Fallback if failed
      nextNo = "999";
    }

    const nomorSurat = `${nextNo}/MSW-KEU/${getRomawiBulan(dateObj.getMonth() + 1)}/${year}`;

    // 2. Generate PDF
    const templatePath = path.join(process.cwd(), 'public', 'images', 'template_kuitansi.png');
    if (!fs.existsSync(templatePath)) {
      return NextResponse.json({ error: 'Template file not found' }, { status: 500 });
    }
    const templateBytes = fs.readFileSync(templatePath);

    const pdfDoc = await PDFDocument.create();
    const image = await pdfDoc.embedPng(templateBytes);
    const { width, height } = image.scale(1); // Get original dimensions
    
    // We will use A4 landscape or match image dimensions
    const page = pdfDoc.addPage([width, height]);
    page.drawImage(image, {
      x: 0,
      y: 0,
      width,
      height,
    });

    // Coordinates for text (these may need tuning based on the actual template_kuitansi.png)
    // The image size is 6000x2765 according to the screenshot in file explorer!
    // That's huge. We'll scale the font size and coordinates proportionally.
    // Alternatively, pdf-lib uses points. 6000 pixels at 72 PPI is 6000 points.
    // Let's use proportional coordinates.
    // Telah diterima dari: X ~ 2200, Y ~ 2050 (from bottom)
    // Uang sejumlah: X ~ 2200, Y ~ 1850
    // Terbilang: X ~ 2200, Y ~ 1650
    // Untuk: X ~ 2200, Y ~ 1450
    // Jakarta, 04-09-2026: X ~ 4200, Y ~ 950
    // No: X ~ 4900, Y ~ 450
    
    const fontSize = 80;
    const fontColor = rgb(0, 0, 0);

    // Coordinate mapping (Origin is bottom-left in PDF-lib)
    // Image height is 2765. 
    // Y is from bottom.
    page.drawText(namaJamaah, { x: 2350, y: 2765 - 1280, size: 90, color: fontColor });
    page.drawText(`Rp ${nominalAngka.toLocaleString('id-ID')}`, { x: 2350, y: 2765 - 1500, size: 90, color: fontColor });
    
    // Terbilang bisa panjang, kita batasi lebarnya atau gunakan font lebih kecil
    page.drawText(terbilangText, { x: 2350, y: 2765 - 1730, size: 70, color: fontColor });
    
    // Untuk Pembayaran
    page.drawText(untukTeks, { x: 2350, y: 2765 - 1950, size: 80, color: fontColor });
    
    // Tanggal di atas stempel
    const tglText = `Jakarta, ${formattedDateStr}`;
    page.drawText(tglText, { x: 3800, y: 2765 - 2000, size: 70, color: fontColor });
    
    // Nomor Surat di kanan bawah
    page.drawText(`No: ${nomorSurat}`, { x: 4700, y: 2765 - 2450, size: 70, color: fontColor });

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Kuitansi_${namaJamaah.replace(/\s+/g, '_')}_${formattedDateStr}.pdf"`
      }
    });

  } catch (error: any) {
    console.error("Error generating kuitansi:", error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
